#dist: trusty
sudo: false
language: java
services: docker
addons:
  hosts:
    - mariadb.example.com
jdk: openjdk11

before_install:
  - git clone https://github.com/rusher/connector-test-machine.git
  - run connector-test-machine/launch
  - echo "MAVEN_OPTS='-Xmx384m'" > ~/.mavenrc

install:
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export PROJ_PATH=`pwd`
  - export SSLCERT=$PROJ_PATH/tmp
  - export TEST_SERVER_SSL_CERT=$SSLCERT/server.crt
  - export TEST_CLIENT_SSL_CERT=$SSLCERT/client.crt
  - export TEST_CLIENT_KEY=$SSLCERT/client.key

cache:
  directories:
    - $HOME/.m2

matrix:
  allow_failures:
    - env: srv=build v=10.6
    - env: srv=mysql v=5.7
    - env: srv=mysql v=8.0
  include:
    - env: srv=skysql
    - env: srv=skysql-ha
    - env: srv=mariadb v=10.2
    - env: srv=mariadb v=10.3
    - env: srv=mariadb v=10.4
    - env: srv=mariadb v=10.5
    - env: srv=mariadb v=10.5 NO_BACKSLASH_ESCAPES=true
    - env: srv=mariadb v=10.5 BENCH=1
    - env: srv=maxscale
    - env: srv=build v=10.6
    - env: srv=mysql v=5.7
    - env: srv=mysql v=8.0

script:
  - git clone https://github.com/rusher/connector-test-machine.git
  - connector-test-machine/launch.sh -t$srv -s$CONNECTOR_TEST_SECRET_KEY -v$v
  - if [[ -n "$BENCH" ]] ; then mvn clean package -P bench -Dmaven.test.skip; fi
  - if [[ -n "$BENCH" ]] ; then java -Duser.country=US -Duser.language=en -DTEST_PORT=$TEST_DB_PORT -DTEST_HOST=$TEST_DB_HOST -DTEST_USERNAME=$TEST_DB_USER -jar target/benchmarks.jar; fi
  - if [[ -z "$BENCH" ]] ; then mvn clean test -DjobId=${TRAVIS_JOB_ID}; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
